### PR TITLE
52 handle cassandra outage

### LINKED ISSUE #52: Add Tests for Cassandra
- Tests for when Cassandra is not available
- Tests for wrong Cassandra credentials

### PR DESCRIPTION
**Pull request by harti2006**
fixes #52 

Well, this PR got bigger than I planned ;-)
I started using the `@ConditionalOn...` annotation of Spring Boot, to create a cleaner configuration. See `CassandraConfig` and `StorageConfig` (and its two inner classes) for example.
However I struggled with the order in which the conditions were evaluated and found out, that `@AutoconfigureAfter` does only work when used with spring.factories (instead of component-scanning all `@Configuration` beans). Thus I decided to remove the global `@ComponentScan` and introduced the `META-INF/spring.factories` file, which contains a list of config classes that should be picked up by `@EnableAutoConfiguration`. This is my opinion, the cleaner way of constructing a Spring context and it eliminates the errors that came from accidentally picked up test config classes.

But of course I also handled the initial issue #52 and introduced the CassandraHealthIndicator as well as a bunch of tests: `CassandraConfigIT`, `HealthCheckIT` to show what happens if wrong credentials are provided or the app gets disconnected from Cassandra.

### CODE REVIEW

File: src/main/java/org/zalando/planb/revocation/persistence/InMemoryRevocationStore.java [hunk 1]
```diff
@@ -25,7 +30,9 @@
 
     @Override
     public void storeRevocation(final RevocationRequest revocation) {
-        revocations.add(ImmutableRevocationData.builder().revocationRequest(revocation).build());
+        final RevocationData revocationData = ImmutableRevocationData.builder().revocationRequest(revocation).build();
+        log.debug("Store revocation in memory: {}", revocationData);
```
Comment (gargravarr) [inline src/main/java/org/zalando/planb/revocation/persistence/InMemoryRevocationStore.java]: This will show plain text Tokens and Claims

Comment (gargravarr) [inline src/main/java/org/zalando/planb/revocation/persistence/InMemoryRevocationStore.java]: Since it's InMemory, not that important though.

**Comment by gargravarr** [comment]
:+1:
